sudo: required

before_install:
  - docker-compose/.travis-update-docker-compose

services:
  - docker

script:
  - docker build -t weblate/weblate:latest . || travis_terminate 1
  - cd docker-compose
  - ./test.sh
  - VOLUMEPATH=$(docker volume inspect -f '{{.Mountpoint}}' wl_weblate-data)
  - sudo mkdir -p $VOLUMEPATH/ssl
  - sudo openssl req -x509 -nodes -days 365 -subj "/CN=weblate.example.com" -newkey rsa:2048 -keyout $VOLUMEPATH/ssl/privkey.pem -out $VOLUMEPATH/ssl/fullchain.pem
  - sudo chown -R 1000:1000 $VOLUMEPATH/ssl
  - ./test.sh 4443 https no

addons:
  apt:
    packages:
      - docker-ce
